apiVersion: workload.nephio.org/v1alpha1
kind: NFConfig
metadata:
  name: cucp-nf-config
  namespace: example
spec:
  configRefs:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: RANConfig
    metadata:
      name: ranconfig
      namespace: default
    spec:
      cellIdentity: 12345678L
      physicalCellID: 0
      tac: 1
      downlinkFrequencyBand: 78
      downlinkSubCarrierSpacing: 1
      downlinkCarrierBandwidth: 51
      uplinkFrequencyBand: 78
      uplinkSubCarrierSpacing: 1
      uplinkCarrierBandwidth: 51
  - apiVersion: workload.nephio.org/v1alpha1
    kind: PLMN
    metadata:
      name: plmn
      namespace: default
    spec:
      PLMNInfo:
      - plmnID:
          mcc: "001"
          mnc: "01"
        tac: 1
        nssai:
        - sd: 0x000000
          sst: 1
  - apiVersion: workload.nephio.org/v1alpha1
    kind: OAIConfig
    metadata:
      name: oai-nf-config
      namespace: default
    spec:
      # The following image is temporary and will be replaced in the future
      image: "ghcr.io/ios-mcn/ios-mcn-gnb-dist:v0.1.4.rc4"
