apiVersion: req.nephio.org/v1alpha1
kind: Dependency
metadata:
  name: amf
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.cucp-example
    specializer.nephio.org/namespace: example
spec:
  packageName: sdcore5g-amf
  injectors:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: NFDeployment
